version: '3.3'

networks:
  my_network:
    ipam:
        config:
          - subnet: 172.31.20.240/16
  
services:
  db:
    build: 
      context: banco-de-dados
      dockerfile: ./Dockerfile
    ports:
      - "3306:3306"
    image: imagem-mysql:latest
    volumes:
      - mysql_data:/var/lib/mysql
    env_file:
      - ./config/db.env
    networks:
      my_network:
        ipv4_address: 172.31.20.240
  
  app:
    depends_on:
      - db
    build: ./aplicacao
    ports:
      - "5000:5000"
    volumes:
      - ./aplicacao:/app
      - ./uploads:/app/uploads
    env_file:
      - ./config/app.env

  
volumes:
  mysql_data: {}
