version: '3.8'

services:
  app:
    depends_on:
      - db
    build: ./aplicacao
    ports:
      - "5000:5000"
    volumes:
      - ./aplicacao:/app
      - ./config/app.env
      - ./uploads:/app/uploads
    networks:
      - my_network

  db:
    build: 
      context: banco-de-dados
      dockerfile: ./Dockerfile
    ports:
      - "3306:3306"
    image: imagem-mysql:latest
    volumes:
      - mysql_data:/var/lib/mysql
      - ./my.cnf:/etc/mysql/my.cnf
    env_file:
      - ./config/db.env
    networks:
      - my_network    
networks:
  my_network:

volumes:
  mysql_data:
