version: '3.8'

services:
  app:
    depends_on:
      - db
    build: ./aplicacao
    ports:
      - "5000:5000"
    volumes:
      - ./uploads:/app/uploads
      - ./config/app.env
    env_file:
      - ./config/app.env
    volumes:
      - ./aplicacao:/app
    networks:
      - my_network
  
  db:
    image: mysql:latest
    volumes:
      - mysql_data:/var/lib/mysql
      - ./my.cnf:/etc/mysql/my.cnf
      - ./config/db.env
    ports:
      - "3306:3306"
    networks:
      - my_network
      
networks:
  my_network:

volumes:
  mysql_data:
